
spring:
    main: 
        banner_mode: off
    data:
        mongodb:
            uri: mongodb://localhost:27017/pids

server:
    port: ${port:8080}
    compression:
        enabled: true

---

spring:
    profiles: development
server:
    port: 9001

---

spring:
    profiles: production
server:
    port: 0

multipart:
    maxFileSize: 3Mb
    maxRequestSize: 20Mb